const express = require('express');
const controller = require('../controllers/adminDashboardController');
const transcripts = require('../controllers/transcriptController');
const authController = require('../controllers/authController');
const authMiddleware = require('../middleware/authMiddleware');
const { authorizeRole, authorizeICT } = require('../middleware/adminMiddleware');
const { documentsUpload } = require('../middleware/uploadMiddleware');
const emailController = require('../controllers/emailController');
const emailNetworkDiagnostic = require('../controllers/emailNetworkDiagnosticController');
const ictController = require('../controllers/ictController');

const router = express.Router();

router.get('/stats', authMiddleware, authorizeRole(['admin', 'rba']), controller.getStats);
router.get('/security-dashboard', authMiddleware, authorizeRole(['admin', 'rba']), controller.getSecurityDashboard);
router.post('/password-reset/request', authMiddleware, authorizeRole(['admin', 'rba']), authController.requestPasswordReset);
router.post('/password-reset/direct', authMiddleware, authorizeRole(['admin', 'rba']), controller.resetStudentPassword);
router.get('/students', authMiddleware, authorizeRole(['admin', 'rba']), controller.getStudents);
router.get('/roles/teachers', authMiddleware, authorizeRole(['admin', 'rba']), controller.getTeachersWithAssignments);
router.post('/roles/teachers', authMiddleware, authorizeRole(['admin', 'rba']), controller.createTeacherWithAssignments);
router.put('/roles/teachers/:teacherId/assignments', authMiddleware, authorizeRole(['admin', 'rba']), controller.updateTeacherAssignments);
router.get('/roles/finance', authMiddleware, authorizeRole(['admin', 'rba']), controller.getFinanceAccounts);
router.post('/roles/finance', authMiddleware, authorizeRole(['admin', 'rba']), controller.createFinanceAccount);
router.get('/roles/ict', authMiddleware, authorizeRole(['admin', 'rba']), controller.getICTAccounts);
router.post('/roles/ict', authMiddleware, authorizeRole(['admin', 'rba']), controller.createICTAccount);
router.get('/email/recipients', authMiddleware, authorizeRole(['admin', 'ict']), emailController.recipients);
router.get('/email/status', authMiddleware, authorizeRole(['admin', 'ict']), emailController.status);
router.post('/email/send', authMiddleware, authorizeRole(['admin', 'ict']), emailController.send);
router.post('/email/test', authMiddleware, authorizeRole(['admin', 'ict']), emailController.test);
router.get('/email/network-diagnostic', authMiddleware, authorizeRole(['admin']), emailNetworkDiagnostic.networkDiagnostic);
router.get('/ict/dashboard', authMiddleware, authorizeICT(['system.manage']), ictController.dashboard);
router.get('/ict/health', authMiddleware, authorizeICT(['system.manage']), ictController.health);
router.get('/ict/users', authMiddleware, authorizeICT(['users.manage']), ictController.users);
router.put('/ict/users/:id', authMiddleware, authorizeICT(['users.manage']), ictController.updateUser);
router.post('/ict/users/:id/reset-password', authMiddleware, authorizeICT(['users.manage']), ictController.resetUser);
router.get('/ict/sessions', authMiddleware, authorizeICT(['security.view']), ictController.sessions);
router.post('/ict/sessions/:id/revoke', authMiddleware, authorizeICT(['security.view']), ictController.revokeSession);
router.get('/ict/audit-logs', authMiddleware, authorizeICT(['security.view']), ictController.auditLogs);
router.get('/ict/permissions', authMiddleware, authorizeICT(['users.manage']), ictController.permissionsList);
router.put('/ict/permissions', authMiddleware, authorizeICT(['users.manage']), ictController.updatePermission);
router.get('/ict/settings', authMiddleware, authorizeICT(['system.manage']), ictController.settings);
router.put('/ict/settings', authMiddleware, authorizeICT(['system.manage']), ictController.saveSettings);
router.put('/ict/maintenance', authMiddleware, authorizeICT(['maintenance.manage']), ictController.maintenance);
router.get('/ict/backups', authMiddleware, authorizeICT(['backups.manage']), ictController.backupHistory);
router.post('/ict/backups', authMiddleware, authorizeICT(['backups.manage']), ictController.createBackup);
router.get('/ict/storage', authMiddleware, authorizeICT(['system.manage']), ictController.storage);
router.get('/ict/database', authMiddleware, authorizeICT(['system.manage']), ictController.database);
router.get('/ict/tickets', authMiddleware, authorizeICT(['system.manage']), ictController.tickets);
router.post('/ict/tickets', authMiddleware, authorizeICT(['system.manage']), ictController.createTicket);
router.put('/ict/tickets/:id', authMiddleware, authorizeICT(['system.manage']), ictController.updateTicket);
router.post('/students', authMiddleware, authorizeRole(['admin', 'rba']), controller.createStudent);
router.put('/students/:studentId/deactivate', authMiddleware, authorizeRole(['admin', 'rba']), controller.deactivateStudent);
router.get('/settings/public', controller.getPublicSettings);
router.get('/settings', authMiddleware, authorizeRole(['admin', 'rba']), controller.getSettings);
router.post('/settings', authMiddleware, authorizeRole(['admin', 'rba']), controller.saveSettings);
router.get('/database', authMiddleware, authorizeRole(['admin', 'rba']), controller.getDatabaseOverview);
router.get('/database/tables/:tableName', authMiddleware, authorizeRole(['admin', 'rba']), controller.getDatabaseTable);
router.post('/database/tables/:tableName', authMiddleware, authorizeRole(['admin', 'rba']), controller.createDatabaseRecord);
router.put('/database/tables/:tableName/:id', authMiddleware, authorizeRole(['admin', 'rba']), controller.updateDatabaseRecord);
router.delete('/database/tables/:tableName/:id', authMiddleware, authorizeRole(['admin', 'rba']), controller.deleteDatabaseRecord);
router.post('/database/query', authMiddleware, authorizeRole(['admin', 'rba']), controller.runDatabaseQuery);
router.get('/transcripts', authMiddleware, authorizeRole(['admin', 'rba']), transcripts.listTranscripts);
router.get('/transcripts/sheets', authMiddleware, authorizeRole(['admin', 'rba']), transcripts.listTranscriptSheets);
router.get('/transcripts/sheet', authMiddleware, authorizeRole(['admin', 'rba']), transcripts.getTranscriptSheet);
router.post('/transcripts/sheet', authMiddleware, authorizeRole(['admin', 'rba']), transcripts.saveTranscriptSheet);
router.post('/transcripts', authMiddleware, authorizeRole(['admin', 'rba']), transcripts.createTranscript);
router.put('/transcripts/:id', authMiddleware, authorizeRole(['admin', 'rba']), transcripts.updateTranscript);
router.delete('/transcripts/:id', authMiddleware, authorizeRole(['admin', 'rba']), transcripts.deleteTranscript);
router.post('/transcripts/upload_csv', authMiddleware, authorizeRole(['admin', 'rba']), documentsUpload.single('file'), transcripts.uploadCsv);
router.get('/transcripts/students', authMiddleware, authorizeRole(['admin', 'rba']), transcripts.getStudentsForNewSheet);

module.exports = router;
